
DROP TABLE  IF EXISTS Users;
DROP TABLE IF EXISTS Posts;
DROP TABLE IF EXISTS Stories;
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS Likes;
DROP TABLE IF EXISTS Follows;

CREATE TABLE Users(
id INTEGER PRIMARY KEY AUTOINCREMENT  ,
name TEXT NOT NULL,
username TEXT  UNIQUE NOT NULL ,
email  TEXT UNIQUE NOT NULL ,
age INTEGER ,
city TEXT,
bio TEXT
);

CREATE TABLE Posts(
id INTEGER PRIMARY KEY AUTOINCREMENT,
userId INTEGER NOT NULL,
imageUrl TEXT ,
caption  TEXT NOT NULL,
createdAt  DATETIME DEFAULT CURRENT_TIMESTAMP,
status TEXT NOT NULL,
FOREIGN KEY  (userId) REFERENCES  Users(id)
);

CREATE TABLE Stories(
id INTEGER PRIMARY KEY AUTOINCREMENT,
userId INTEGER NOT NULL,
imageUrl TEXT,
createdAt  DATETIME DEFAULT CURRENT_TIMESTAMP,
expiresAt   DATETIME ,
FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE Comments(
id INTEGER PRIMARY KEY AUTOINCREMENT,
postId INTEGER NOT NULL,
userId INTEGER NOT NULL,
content TEXT NOT NULL,
createdAt  DATETIME DEFAULT CURRENT_TIMESTAMP ,
FOREIGN KEY (postId) REFERENCES Posts(id),
FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE Likes(
id INTEGER PRIMARY KEY AUTOINCREMENT,
postId INTEGER NOT NULL,
userId INTEGER NOT NULL,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (postId) REFERENCES Posts(id),
FOREIGN KEY (userId) REFERENCES Users(id)
);
CREATE TABLE Follows(
id INTEGER PRIMARY KEY AUTOINCREMENT,
followerId   INTEGER NOT NULL,
followingId  INTEGER NOT NULL,
createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (followerId ) REFERENCES Users(id),
FOREIGN KEY (followingId ) REFERENCES Users(id)
);